### ISSUE TITLE
ssl_client2.c certificate failure

### ISSUE THREAD

**Issue by ryandeng1** [hannestschofenig/mbedtls#54]
I tried having the ssl_client2.c ping a known website, specifically yahoo.com on port 80, which leads to the following error:
```
Last error was: -0x7200 - SSL - An invalid SSL record was received
```

I also tried having it ping smtp.gmail.com on port 465, which results in this error:
```
Last error was: -0x2700 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
```

I incorporated the latest changes in the tls13-prototype branch and also incorporated the latest changes in PR #52. I was wondering if there was anything I might need to do locally beforehand to make it run with websites?

Thanks

**Comment by weikengchen** [comment]
~Seems the second issue is due to the lack of `ca_file`, which could be solved by:~

~`./ssl_client2 auth_mode=optional`~

The problem seems remained in TLS 1.3 branch.

**Comment by weikengchen** [comment]
~And for the first one, it is expected---the port number should be 443 instead. I tested it and it seems to work.~

**Comment by weikengchen** [comment]
It seems that the error remains in the TLS 1.3 branch. (I previously tested on the `development` branch)

**Comment by hannestschofenig** [comment]
I fixed this bug in https://github.com/hannestschofenig/mbedtls/pull/52. 

(FWIW #51 and #50 also needs to be approved as well.)

We are trying to merge these three PRs asap and then we should test again. Thanks for looking at this.

**Comment by zhihan** [comment]
Not sure if #52 alone can fix the problem. I patched it and it still gives me error:
```
ssl_client2 server_name=enabled.tls13.com server_port=443 ca_file=/etc/ssl/cert.pem debug_level=5                   
Building: finished in 0.2 sec (100%) 6/120 jobs, 0 updated
  Total time: 0.2 sec

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (114 skipped)
  . Loading the client cert. and key... ok (key type: EC)
  . Connecting to tcp/enabled.tls13.com/443... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...
Verify requested for (Depth 0):
cert. version     : 3
serial number     : 02:A7:C1:95:57:7F:F0:E9:0C:35:99:61:D2:04:B0:ED
issuer name       : C=US, O=Cloudflare, Inc., CN=Cloudflare Inc ECC CA-3
subject name      : C=US, ST=CA, L=San Francisco, O=Cloudflare, Inc., CN=sni.cloudflaressl.com
issued  on        : 2020-08-17 00:00:00
expires on        : 2021-08-17 12:00:00
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  :
    dNSName : tls13.com
    dNSName : *.tls13.com
    dNSName : sni.cloudflaressl.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
certificate policies : ???, ???
  ! The certificate is not correctly signed by the trusted CA

 failed
  ! mbedtls_ssl_handshake returned -0x2700
    Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes.

Last error was: -0x2700 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
```
If I change the auth_mode to optional, it goes one step further but still has errors.
```
ssl_client2 server_name=enabled.tls13.com server_port=443 ca_file=/etc/ssl/cert.pem auth_mode=optional
Building: finished in 0.2 sec (100%) 6/6 jobs, 0 updated
  Total time: 0.2 sec

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (114 skipped)
  . Loading the client cert. and key... ok (key type: EC)
  . Connecting to tcp/enabled.tls13.com/443... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...
Verify requested for (Depth 0):
cert. version     : 3
serial number     : 02:A7:C1:95:57:7F:F0:E9:0C:35:99:61:D2:04:B0:ED
issuer name       : C=US, O=Cloudflare, Inc., CN=Cloudflare Inc ECC CA-3
subject name      : C=US, ST=CA, L=San Francisco, O=Cloudflare, Inc., CN=sni.cloudflaressl.com
issued  on        : 2020-08-17 00:00:00
expires on        : 2021-08-17 12:00:00
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  :
    dNSName : tls13.com
    dNSName : *.tls13.com
    dNSName : sni.cloudflaressl.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
certificate policies : ???, ???
  ! The certificate is not correctly signed by the trusted CA

 ok
    [ Protocol is TLSv1.3 ]
    [ Ciphersuite is TLS_AES_256_GCM_SHA384 ]
    [ Key Exchange Mode is ECDHE-ECDSA ]
    [ Record expansion (outgoing) is 5 ]
    [ Record expansion (incoming) is 5 ]
  . Verifying peer X.509 certificate... failed
  ! The certificate is not correctly signed by the trusted CA

  . Peer certificate information    ...
cert. version     : 3
serial number     : 02:A7:C1:95:57:7F:F0:E9:0C:35:99:61:D2:04:B0:ED
issuer name       : C=US, O=Cloudflare, Inc., CN=Cloudflare Inc ECC CA-3
subject name      : C=US, ST=CA, L=San Francisco, O=Cloudflare, Inc., CN=sni.cloudflaressl.com
issued  on        : 2020-08-17 00:00:00
expires on        : 2021-08-17 12:00:00
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  :
    dNSName : tls13.com
    dNSName : *.tls13.com
    dNSName : sni.cloudflaressl.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
certificate policies : ???, ???

  > Write to server: 35 bytes written in 1 fragments

GET / HTTP/1.0
Extra-header: 


  < Read from server: mbedtls_ssl_read returned -0x6e00
Last error was: -0x6E00 - SSL - Processing of the NewSessionTicket handshake message failed
```

**Comment by zhihan** [comment]
I also patched the other two PRs. Still the same problem. Attached two debug logs (TLSv1.3 and TLSv1.2 w/ development) to compare. The decrypted buffer of TLS13 looks wrong.
[mbedtls_tls13_patched.log](https://github.com/hannestschofenig/mbedtls/files/5503600/mbedtls_tls13_patched.log)
[mbedtls_tlsv12.log](https://github.com/hannestschofenig/mbedtls/files/5503601/mbedtls_tlsv12.log)

**Comment by hannestschofenig** [comment]
Thanks for these logs and for raising these issues. 

I have been able to reproduce the bug and I can see what the problem is. I have to figure out why this situation occurs. In a nutshell, I am checking the length of the new_session_ticket message against the length of the input buffer and that seems incorrect because the input buffer already contains the response from the HTTP server. So, I will have to fix the length checking here.

**Comment by hannestschofenig** [comment]
FWIW if I remove the length checking in the mbedtls_ssl_parse_new_session_ticket() function the server connects correctly. 

I am planning to resolve this issue in the next few days.

**Comment by zhihan** [comment]
Thanks, I am observing the same behavior. Not sure if it is OK to only parse the first NewSessionTicket message and ignoring the rest, but commenting out the length check will stop the error.

**Comment by hannestschofenig** [comment]
Here is a quick PR that may help to resolve this issue: https://github.com/hannestschofenig/mbedtls/pull/61

**Comment by hanno-becker** [comment]
@zhihan @hannestschofenig Could you give an update on this issue? Is it still unresolved?

**Comment by zhihan** [comment]
It is fixed. Thanks!
